### ISSUE TITLE
test.tscn Unexpected end of file

### ISSUE THREAD

**Issue by JaspervanderSter** [RodZill4/godot-music#1]
First of all I think you did an amazing job on integrating TSF in Godot and I would love to check it out!

I cloned the project and tried to load it with Godot, but when I want to open the test.tscn, I encounter the error: "Unexpected end of file 'test.tscn'".

The error in the console says: "Can't create sub resource of type: AudioStreamGenerator".

Do you have any clue what I did wrong? Thanks a lot in advance!

I am using Godot 3.1 on a Windows 10 OS.

**Comment by RodZill4** [comment]
Not sure, but I think AudioStreamGenerator was introduced in Godot 3.1.1. Could you test with this release ?

**Comment by JaspervanderSter** [comment]
You're absolutely right! I used 3.1, but with 3.1.1 it seems to be working!

It might not be the appropiate place to say this, but I really appreciate the work you did here, thanks a lot!
